version: "3.9"

services:
#  app:
#    image: 'dictionary-service:latest'
#    container_name: 'dictionary-service'
#    environment:
#    ports:
#      - '8181:8181'
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=dictionary-service-db
      - MONGO_INITDB_ROOT_USERNAME=adminUser
      - MONGO_INITDB_ROOT_PASSWORD=adminPass
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

