version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'dictionary-service'
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=dictionary-service-db
      - DB_USER=appUser
      - DB_PASSWORD=appPass
    ports:
      - '8282:8181'
  mongodb:
    image: 'mongo:4.0.8'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=dictionary-service-db
      - MONGO_INITDB_ROOT_USERNAME=adminUser
      - MONGO_INITDB_ROOT_PASSWORD=adminPass
    ports:
      - '27017:27017'
    volumes:
      - docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

