server:
  port: 8181
  error:
    path: /error
spring:
  data:
    mongodb:
      uri: ${DB_URL:mongodb://dictUser:dictPass@localhost:27017/dictionary-service-db}
  jackson:
    default-property-inclusion: non_null
app:
  dictionary-api-url: ${DICT_API_URL:https://api.dictionaryapi.dev/api/v2/entries/en/}
