apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-svc"
  namespace: "{{ .Values.appName }}-ns"
  labels:
    app: "{{ .Values.appName }}"
spec:
  selector:
    app: "{{ .Values.appName }}-app"
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8181
