apiVersion: v1
kind: Pod
metadata:
  name: target-pod
  namespace: "{{ .Values.appName }}-ns"
  labels:
    name: target-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: 1Gi
          cpu: 0.5