apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Values.appName }}-netpol"
  namespace: "{{ .Values.appName }}-ns"
spec:
  podSelector:
    matchLabels:
      app: mongodb
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              ns-type: app-ns
        - podSelector:
            matchLabels:
              name: "{{ .Values.microserviceName }}"
      ports:
        - protocol: TCP
          port: 27017