apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-mongodb-svc"
  namespace: "{{ .Values.appName }}-ns"
  labels:
    app: "{{ .Values.appName }}"
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017