apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appName }}-cm"
  namespace: "{{ .Values.appName }}-ns"
  labels:
    app: "{{ .Values.appName }}"
data:
  DICT_API_URL: https://api.dictionaryapi.dev/api/v2/entries/en/