apiVersion: v1
kind: Pod
metadata:
  name: dns-test
  namespace: "{{ .Values.appName }}-ns"
spec:
  containers:
    - image: busybox:latest
      name: dns-test
      resources:
        requests:
          memory: 100Mi
          cpu: 0.2
      command:
        - /bin/sh
        - -c
        - sleep 3600
  #      - ping dictionary-service-mongodb-sts-0.dictionary-service-mongodb-svc.dictionary-service-ns.svc.cluster.local
  dnsPolicy: ClusterFirst
  restartPolicy: Always
