apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appName }}-secret"
  namespace: "{{ .Values.appName }}-ns"
  labels:
    app: "{{ .Values.appName }}"
data:
  DB_HOST: ZGF0YWJhc2UtbW9uZ29kYi1zdmMuZGF0YWJhc2UtbnMuc3ZjLmNsdXN0ZXIubG9jYWw=
  #DB_HOST: database-mongodb-svc.database-ns.svc.cluster.local
  DB_PORT: MjcwMTc=
  #DB_PORT: 27017
  DB_NAME: ZGljdGlvbmFyeS1zZXJ2aWNlLWRi
  #DB_NAME: dictionary-service-db
  #DB_USER: ZGljdFVzZXI=
  #DB_USER: dictUser
  #DB_PASSWORD: ZGljdFBhc3M=
  #DB_PASSWORD: dictPass
  DB_USER: YWRtaW4=
  #DB_USER: admin
  DB_PASSWORD: cGFzc3dvcmQK
  #DB_PASSWORD: password
